### ISSUE TITLE
Crash in Production

### ISSUE THREAD

**Issue by annakozy2011** [morinel/gcmpush#36]
I have 12 of these crash reports in release: 

java.lang.NullPointerException: Attempt to invoke virtual method 'void nl.vanvianen.android.gcm.GCMModule.sendSuccess(java.lang.String)' on a null object reference
	at nl.vanvianen.android.gcm.GCMIntentService.onRegistered(GCMIntentService.java:58)
	at com.google.android.gcm.GCMBaseIntentService.handleRegistration(GCMBaseIntentService.java:295)
	at com.google.android.gcm.GCMBaseIntentService.onHandleIntent(GCMBaseIntentService.java:197)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by annakozy2011** [comment]
We reproduced this crash in development. 

It's indeed line 108 of GCMIntentService, before calling value.startsWith, you need to check if value is not null

**Comment by annakozy2011** [comment]
![image](https://cloud.githubusercontent.com/assets/724597/17507577/ac2e029a-5e10-11e6-89a3-da6cdc000f30.png)

**Comment by annakozy2011** [comment]
I was using version 1.6 of the module, maybe it's outdated already?

**Comment by morinel** [comment]
Try version 1.7 I released yesterday.
