### ISSUE TITLE
no compile sdK 6.1.1

### ISSUE THREAD

**Issue by necrocyber** [morinel/gcmpush#61]
this error please

[ERROR] :  Failed to run dexer:
[ERROR] :  
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/gcm/GcmListenerService;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/gcm/GcmListenerService$1;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/gcm/GcmListenerService$2;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/gcm/GcmNetworkManager;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/gcm/GcmPubSub;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/gcm/GcmReceiver;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/gcm/GcmTaskService;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/gcm/GcmTaskService$zza;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/gcm/GoogleCloudMessaging;
[ERROR] :  
[ERROR] :  UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] :  java.lang.RuntimeException: Translation has been interrupted
[ERROR] :  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:615)
[ERROR] :  	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:368)
[ERROR] :  	at com.android.dx.command.dexer.Main.runDx(Main.java:289)
[ERROR] :  	at com.android.dx.command.dexer.Main.main(Main.java:247)
[ERROR] :  	at com.android.dx.command.Main.main(Main.java:94)
[ERROR] :  Caused by: java.lang.InterruptedException: Too many errors
[ERROR] :  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:607)
[ERROR] :  	... 4 more

**Comment by mcvendrell** [comment]
Comming to say the same:

Ti SDK 6.1.2 and I get this error:
08-08 12:42:41.679: E/AndroidRuntime(3078): java.lang.UnsatisfiedLinkError: Cannot load library: link_image[1962]:   101 could not load needed library 'libstlport_shared.so' for 'libnl.vanvianen.android.gcm.so' (load_library[1117]: Library 'libstlport_shared.so' not found)

**Comment by mcvendrell** [comment]
I will autorespond: there is a fork updated with 6.x

https://github.com/skypanther/gcmpush/tree/master/dist

**Comment by vasilestefirta** [comment]
@mcvendrell The module from the link you've provided works just fine w/ Ti SDK 6+, however I'm experiencing an issue when the Push Notification does not show up when the app is closed/background (even if I can see some console logs regarding that the push notification message was received). Do you know by chance what can cause that problem? Thanks! :+1:

**Comment by mcvendrell** [comment]
Hi @vasilestefirta . I have no issues with this module. Works well for me, no matter if app is closed or backgrounded.
Just be sure that the expected payload from the server is right (if you are building the payload manually)

**Comment by vasilestefirta** [comment]
Interesting! Do you mind sharing your implementation for `gcm.registerPush()` method and your `<android>...</android>` section from your project's `tiapp.xml` file? I would really appreciate that! :pray:

**Comment by mcvendrell** [comment]
Of course, nothing special (*GCMsender...* is the name for the FCM id):

`	gcm.registerPush({
		senderId: Alloy.CFG.GCMsenderNotifId,
		notificationSettings: {
			smallIcon: 'notify.png',  // Place icon in platform/android/res/drawable/
			largeIcon: 'notify.png',  // Same
			vibrate: true,  // Whether the phone should vibrate
                        sound: 'default',
		},
        success: deviceTokenSuccess, // Success returns event.registrationId
        error: deviceTokenError, // Error returns event.error
		callback: receivePushMessage // Callback returns event.data
	});
`

And nothing in the tiapp.xml, this module doesn't need it.

**Comment by vasilestefirta** [comment]
@mcvendrell Thanks! It looks like the issue was happening because of the data I was sending from the server. I was sending `text` instead of `message` :simple_smile: Fixed it and now it works just fine!

**Comment by mcvendrell** [comment]
@vasilestefirta that's why I warn about be sure on the payload. Excellent.
