### ISSUE TITLE
Not support for Titanium sdk 6.3.0 ?

### ISSUE THREAD

**Issue by ChanakyaSrinivas** [morinel/gcmpush#63]
I am trying to use this module.
but when I run my app am getting below error.

is this module support for latest Titanium SDK Versions?
In feature are you providing support when new titanium SDK released?

**[ERROR] :**  art: dlopen("/data/app/com.test-1/lib/arm/libnl.vanvianen.android.gcm.so", RTLD_LAZY) failed: dlopen failed: library "libstlport_shared.so" not found
[ERROR] :  TiApplication: (main) [60,1770] Sending event: exception on thread: main msg:java.lang.UnsatisfiedLinkError: dlopen failed: library "libstlport_shared.so" not found; Titanium 6.3.0,2017/10/31 18:13,undefined
[ERROR] :  TiApplication: java.lang.UnsatisfiedLinkError: dlopen failed: library "libstlport_shared.so" not found
[ERROR] :  TiApplication: 	at java.lang.Runtime.loadLibrary(Runtime.java:371)
[ERROR] :  TiApplication: 	at java.lang.System.loadLibrary(System.java:988)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:151)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:118)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:205)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:114)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollRuntime.init(KrollRuntime.java:136)
[ERROR] :  TiApplication: 	at com.test.TestApplication.onCreate(TestApplication.java:46)
[ERROR] :  TiApplication: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1035)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4638)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.access$1500(ActivityThread.java:155)
[ERROR] :  TiApplication: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
[ERROR] :  TiApplication: 	at android.os.Handler.dispatchMessage(Handler.java:102)
[ERROR] :  TiApplication: 	at android.os.Looper.loop(Looper.java:135)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.main(ActivityThread.java:5343)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invoke(Method.java:372)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**My environments:**

Operating System			= Mac OS X 10.11.3
Node.js Version             = 4.6.0
npm Version                 = 2.15.9
Titanium CLI Version        = 5.0.14
Titanium SDK Version        = 6.3.0.GA

**Comment by max1020** [comment]
It is working for me with 6.3 SDK. (with SDK 7.0 the module is greyed out in the modules overview in tiapp).

**Comment by morinel** [comment]
I just updated the module for Ti SDK 7.0.0 which supports a different module manifest version (4).
